/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiClubRouteImport } from './routes/api/club'
import { Route as TomoIdRouteImport } from './routes/tomo.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MediaBookIdKindRouteImport } from './routes/media.$bookId.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClubRoute = ApiClubRouteImport.update({
  id: '/api/club',
  path: '/api/club',
  getParentRoute: () => rootRouteImport,
} as any)
const TomoIdRoute = TomoIdRouteImport.update({
  id: '/tomo/$id',
  path: '/tomo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaBookIdKindRoute = MediaBookIdKindRouteImport.update({
  id: '/media/$bookId/$kind',
  path: '/media/$bookId/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/club': typeof ApiClubRoute
  '/tomo/$id': typeof TomoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/media/$bookId/$kind': typeof MediaBookIdKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/club': typeof ApiClubRoute
  '/tomo/$id': typeof TomoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/media/$bookId/$kind': typeof MediaBookIdKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/club': typeof ApiClubRoute
  '/tomo/$id': typeof TomoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/media/$bookId/$kind': typeof MediaBookIdKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/club'
    | '/tomo/$id'
    | '/api/auth/$'
    | '/media/$bookId/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/club'
    | '/tomo/$id'
    | '/api/auth/$'
    | '/media/$bookId/$kind'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/club'
    | '/tomo/$id'
    | '/api/auth/$'
    | '/media/$bookId/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiClubRoute: typeof ApiClubRoute
  TomoIdRoute: typeof TomoIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MediaBookIdKindRoute: typeof MediaBookIdKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/club': {
      id: '/api/club'
      path: '/api/club'
      fullPath: '/api/club'
      preLoaderRoute: typeof ApiClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tomo/$id': {
      id: '/tomo/$id'
      path: '/tomo/$id'
      fullPath: '/tomo/$id'
      preLoaderRoute: typeof TomoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$bookId/$kind': {
      id: '/media/$bookId/$kind'
      path: '/media/$bookId/$kind'
      fullPath: '/media/$bookId/$kind'
      preLoaderRoute: typeof MediaBookIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiClubRoute: ApiClubRoute,
  TomoIdRoute: TomoIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MediaBookIdKindRoute: MediaBookIdKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
